// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjcinpfmlsrieihycald.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqY2lucGZtbHNyaWVpaHljYWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NDIzNDgsImV4cCI6MjA1NzAxODM0OH0.ta5GNnt9pPsM701C4t7AK5ecD8WsAo4E3AMlCBNIUNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);